logging:
  config: classpath:/log4j2-spring.xml

spring:
  application:
    name: krgs

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs

krgs:
  reverse-country-max-distance-threshold-in-degrees: 2
  open-api-servers: ${OPEN_API_SERVERS}
